# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: E:/rzeczy/vivado_projekty/klt_ddc/klt_ddc.srcs/sources_1/bd/tor_wizyjny/ip/tor_wizyjny_rgb2dvi_0_0/tor_wizyjny_rgb2dvi_0_0.xci
# IP: The module: 'tor_wizyjny_rgb2dvi_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/rzeczy/vivado_projekty/klt_ddc/klt_ddc.srcs/sources_1/bd/tor_wizyjny/ip/tor_wizyjny_rgb2dvi_0_0/src/rgb2dvi.xdc
# XDC: The top module name and the constraint reference have the same name: 'tor_wizyjny_rgb2dvi_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: e:/rzeczy/vivado_projekty/klt_ddc/klt_ddc.srcs/sources_1/bd/tor_wizyjny/ip/tor_wizyjny_rgb2dvi_0_0/src/rgb2dvi_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'tor_wizyjny_rgb2dvi_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: e:/rzeczy/vivado_projekty/klt_ddc/klt_ddc.srcs/sources_1/bd/tor_wizyjny/ip/tor_wizyjny_rgb2dvi_0_0/src/rgb2dvi_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'tor_wizyjny_rgb2dvi_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: E:/rzeczy/vivado_projekty/klt_ddc/klt_ddc.srcs/sources_1/bd/tor_wizyjny/ip/tor_wizyjny_rgb2dvi_0_0/tor_wizyjny_rgb2dvi_0_0.xci
# IP: The module: 'tor_wizyjny_rgb2dvi_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/rzeczy/vivado_projekty/klt_ddc/klt_ddc.srcs/sources_1/bd/tor_wizyjny/ip/tor_wizyjny_rgb2dvi_0_0/src/rgb2dvi.xdc
# XDC: The top module name and the constraint reference have the same name: 'tor_wizyjny_rgb2dvi_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: e:/rzeczy/vivado_projekty/klt_ddc/klt_ddc.srcs/sources_1/bd/tor_wizyjny/ip/tor_wizyjny_rgb2dvi_0_0/src/rgb2dvi_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'tor_wizyjny_rgb2dvi_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: e:/rzeczy/vivado_projekty/klt_ddc/klt_ddc.srcs/sources_1/bd/tor_wizyjny/ip/tor_wizyjny_rgb2dvi_0_0/src/rgb2dvi_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'tor_wizyjny_rgb2dvi_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
