# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: e:/rzeczy/vivado_projekty/klt_pyramid/klt_pyramid.srcs/sources_1/ip/frame_delay_sim_1/frame_delay_sim.xci
# IP: The module: 'frame_delay_sim' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/rzeczy/vivado_projekty/klt_pyramid/klt_pyramid.srcs/sources_1/ip/frame_delay_sim_1/frame_delay_sim_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'frame_delay_sim'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: e:/rzeczy/vivado_projekty/klt_pyramid/klt_pyramid.srcs/sources_1/ip/frame_delay_sim_1/frame_delay_sim.xci
# IP: The module: 'frame_delay_sim' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/rzeczy/vivado_projekty/klt_pyramid/klt_pyramid.srcs/sources_1/ip/frame_delay_sim_1/frame_delay_sim_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'frame_delay_sim'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
