# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: E:/rzeczy/vivado_projekty/klt/klt.srcs/sources_1/ip/sub_8m8/sub_8m8.xci
# IP: The module: 'sub_8m8' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/rzeczy/vivado_projekty/klt/klt.srcs/sources_1/ip/sub_8m8/sub_8m8_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'sub_8m8'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: E:/rzeczy/vivado_projekty/klt/klt.srcs/sources_1/ip/sub_8m8/sub_8m8.xci
# IP: The module: 'sub_8m8' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/rzeczy/vivado_projekty/klt/klt.srcs/sources_1/ip/sub_8m8/sub_8m8_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'sub_8m8'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
