# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/digilent-xdc-master/Zybo-Z7-Master.xdc

# Block Designs: bd/mainBlockDesign/mainBlockDesign.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mainBlockDesign || ORIG_REF_NAME==mainBlockDesign} -quiet] -quiet

# IP: bd/mainBlockDesign/ip/mainBlockDesign_dvi2rgb_0_0/mainBlockDesign_dvi2rgb_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mainBlockDesign_dvi2rgb_0_0 || ORIG_REF_NAME==mainBlockDesign_dvi2rgb_0_0} -quiet] -quiet

# IP: bd/mainBlockDesign/ip/mainBlockDesign_clk_wiz_0_0/mainBlockDesign_clk_wiz_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mainBlockDesign_clk_wiz_0_0 || ORIG_REF_NAME==mainBlockDesign_clk_wiz_0_0} -quiet] -quiet

# IP: bd/mainBlockDesign/ip/mainBlockDesign_rgb2dvi_0_0/mainBlockDesign_rgb2dvi_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mainBlockDesign_rgb2dvi_0_0 || ORIG_REF_NAME==mainBlockDesign_rgb2dvi_0_0} -quiet] -quiet

# IP: bd/mainBlockDesign/ip/mainBlockDesign_xlconstant_0_0/mainBlockDesign_xlconstant_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mainBlockDesign_xlconstant_0_0 || ORIG_REF_NAME==mainBlockDesign_xlconstant_0_0} -quiet] -quiet

# IP: bd/mainBlockDesign/ip/mainBlockDesign_rgb2ycbcr_0_0_1/mainBlockDesign_rgb2ycbcr_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mainBlockDesign_rgb2ycbcr_0_0 || ORIG_REF_NAME==mainBlockDesign_rgb2ycbcr_0_0} -quiet] -quiet

# IP: bd/mainBlockDesign/ip/mainBlockDesign_bbox21_0_0_1/mainBlockDesign_bbox21_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mainBlockDesign_bbox21_0_0 || ORIG_REF_NAME==mainBlockDesign_bbox21_0_0} -quiet] -quiet

# IP: bd/mainBlockDesign/ip/mainBlockDesign_klt_pyramid_tracker_0_0/mainBlockDesign_klt_pyramid_tracker_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mainBlockDesign_klt_pyramid_tracker_0_0 || ORIG_REF_NAME==mainBlockDesign_klt_pyramid_tracker_0_0} -quiet] -quiet

# IP: bd/mainBlockDesign/ip/mainBlockDesign_xlconstant_0_1_1/mainBlockDesign_xlconstant_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mainBlockDesign_xlconstant_0_1 || ORIG_REF_NAME==mainBlockDesign_xlconstant_0_1} -quiet] -quiet

# IP: bd/mainBlockDesign/ip/mainBlockDesign_xlconstant_0_2_1/mainBlockDesign_xlconstant_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mainBlockDesign_xlconstant_0_2 || ORIG_REF_NAME==mainBlockDesign_xlconstant_0_2} -quiet] -quiet

# IP: bd/mainBlockDesign/ip/mainBlockDesign_xlconstant_0_3/mainBlockDesign_xlconstant_0_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mainBlockDesign_xlconstant_0_3 || ORIG_REF_NAME==mainBlockDesign_xlconstant_0_3} -quiet] -quiet

# IP: bd/mainBlockDesign/ip/mainBlockDesign_xlconstant_0_4/mainBlockDesign_xlconstant_0_4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mainBlockDesign_xlconstant_0_4 || ORIG_REF_NAME==mainBlockDesign_xlconstant_0_4} -quiet] -quiet

# IP: bd/mainBlockDesign/ip/mainBlockDesign_deconcat_0_0_1/mainBlockDesign_deconcat_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mainBlockDesign_deconcat_0_0 || ORIG_REF_NAME==mainBlockDesign_deconcat_0_0} -quiet] -quiet

# IP: bd/mainBlockDesign/ip/mainBlockDesign_processing_system7_0_0/mainBlockDesign_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mainBlockDesign_processing_system7_0_0 || ORIG_REF_NAME==mainBlockDesign_processing_system7_0_0} -quiet] -quiet

# IP: bd/mainBlockDesign/ip/mainBlockDesign_hsize_counter_0_0_1/mainBlockDesign_hsize_counter_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mainBlockDesign_hsize_counter_0_0 || ORIG_REF_NAME==mainBlockDesign_hsize_counter_0_0} -quiet] -quiet

# IP: bd/mainBlockDesign/ip/mainBlockDesign_parameter_register_0_0/mainBlockDesign_parameter_register_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mainBlockDesign_parameter_register_0_0 || ORIG_REF_NAME==mainBlockDesign_parameter_register_0_0} -quiet] -quiet

# IP: bd/mainBlockDesign/ip/mainBlockDesign_ps7_0_axi_periph_0/mainBlockDesign_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mainBlockDesign_ps7_0_axi_periph_0 || ORIG_REF_NAME==mainBlockDesign_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/mainBlockDesign/ip/mainBlockDesign_rst_ps7_0_50M_0/mainBlockDesign_rst_ps7_0_50M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mainBlockDesign_rst_ps7_0_50M_0 || ORIG_REF_NAME==mainBlockDesign_rst_ps7_0_50M_0} -quiet] -quiet

# IP: bd/mainBlockDesign/ip/mainBlockDesign_system_ila_0_0_1/mainBlockDesign_system_ila_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mainBlockDesign_system_ila_0_0 || ORIG_REF_NAME==mainBlockDesign_system_ila_0_0} -quiet] -quiet

# IP: bd/mainBlockDesign/ip/mainBlockDesign_auto_pc_0/mainBlockDesign_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mainBlockDesign_auto_pc_0 || ORIG_REF_NAME==mainBlockDesign_auto_pc_0} -quiet] -quiet

# XDC: bd/mainBlockDesign/mainBlockDesign_ooc.xdc
