# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/konkurs/vivado_projekty/czysty_tor/mainVideoProcessing_Zybo-Z20.srcs/sources_1/bd/mainBlockDesign/ip/mainBlockDesign_processing_system7_0_0/mainBlockDesign_processing_system7_0_0.xci
# IP: The module: 'mainBlockDesign_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/konkurs/vivado_projekty/czysty_tor/mainVideoProcessing_Zybo-Z20.srcs/sources_1/bd/mainBlockDesign/ip/mainBlockDesign_processing_system7_0_0/mainBlockDesign_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'mainBlockDesign_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: c:/konkurs/vivado_projekty/czysty_tor/mainVideoProcessing_Zybo-Z20.srcs/sources_1/bd/mainBlockDesign/ip/mainBlockDesign_processing_system7_0_0/mainBlockDesign_processing_system7_0_0.xci
# IP: The module: 'mainBlockDesign_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/konkurs/vivado_projekty/czysty_tor/mainVideoProcessing_Zybo-Z20.srcs/sources_1/bd/mainBlockDesign/ip/mainBlockDesign_processing_system7_0_0/mainBlockDesign_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'mainBlockDesign_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
