# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/digilent-xdc-master/Zybo-Z7-Master.xdc

# Block Designs: bd/mainBlockDesign/mainBlockDesign.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mainBlockDesign || ORIG_REF_NAME==mainBlockDesign} -quiet] -quiet

# IP: bd/mainBlockDesign/ip/mainBlockDesign_dvi2rgb_0_0/mainBlockDesign_dvi2rgb_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mainBlockDesign_dvi2rgb_0_0 || ORIG_REF_NAME==mainBlockDesign_dvi2rgb_0_0} -quiet] -quiet

# IP: bd/mainBlockDesign/ip/mainBlockDesign_clk_wiz_0_0/mainBlockDesign_clk_wiz_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mainBlockDesign_clk_wiz_0_0 || ORIG_REF_NAME==mainBlockDesign_clk_wiz_0_0} -quiet] -quiet

# IP: bd/mainBlockDesign/ip/mainBlockDesign_rgb2dvi_0_0/mainBlockDesign_rgb2dvi_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mainBlockDesign_rgb2dvi_0_0 || ORIG_REF_NAME==mainBlockDesign_rgb2dvi_0_0} -quiet] -quiet

# IP: bd/mainBlockDesign/ip/mainBlockDesign_xlconstant_0_0/mainBlockDesign_xlconstant_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mainBlockDesign_xlconstant_0_0 || ORIG_REF_NAME==mainBlockDesign_xlconstant_0_0} -quiet] -quiet

# IP: bd/mainBlockDesign/ip/mainBlockDesign_KLT_van_0_0/mainBlockDesign_KLT_van_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mainBlockDesign_KLT_van_0_0 || ORIG_REF_NAME==mainBlockDesign_KLT_van_0_0} -quiet] -quiet

# IP: bd/mainBlockDesign/ip/mainBlockDesign_rgb2ycbcr_0_0/mainBlockDesign_rgb2ycbcr_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mainBlockDesign_rgb2ycbcr_0_0 || ORIG_REF_NAME==mainBlockDesign_rgb2ycbcr_0_0} -quiet] -quiet

# IP: bd/mainBlockDesign/ip/mainBlockDesign_xlconstant_0_1/mainBlockDesign_xlconstant_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mainBlockDesign_xlconstant_0_1 || ORIG_REF_NAME==mainBlockDesign_xlconstant_0_1} -quiet] -quiet

# IP: bd/mainBlockDesign/ip/mainBlockDesign_xlconstant_0_2/mainBlockDesign_xlconstant_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mainBlockDesign_xlconstant_0_2 || ORIG_REF_NAME==mainBlockDesign_xlconstant_0_2} -quiet] -quiet

# IP: bd/mainBlockDesign/ip/mainBlockDesign_bbox21_0_0/mainBlockDesign_bbox21_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mainBlockDesign_bbox21_0_0 || ORIG_REF_NAME==mainBlockDesign_bbox21_0_0} -quiet] -quiet

# IP: bd/mainBlockDesign/ip/mainBlockDesign_system_ila_0_0/mainBlockDesign_system_ila_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mainBlockDesign_system_ila_0_0 || ORIG_REF_NAME==mainBlockDesign_system_ila_0_0} -quiet] -quiet

# IP: bd/mainBlockDesign/ip/mainBlockDesign_split_rgb_0_0/mainBlockDesign_split_rgb_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mainBlockDesign_split_rgb_0_0 || ORIG_REF_NAME==mainBlockDesign_split_rgb_0_0} -quiet] -quiet

# XDC: bd/mainBlockDesign/mainBlockDesign_ooc.xdc
