# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/konkurs/vivado_projekty/klt_pyramid/klt_pyramid.srcs/sources_1/ip/prev_context_roi31/prev_context_roi31.xci
# IP: The module: 'prev_context_roi31' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/konkurs/vivado_projekty/klt_pyramid/klt_pyramid.srcs/sources_1/ip/prev_context_roi31/prev_context_roi31_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'prev_context_roi31'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: c:/konkurs/vivado_projekty/klt_pyramid/klt_pyramid.srcs/sources_1/ip/prev_context_roi31/prev_context_roi31.xci
# IP: The module: 'prev_context_roi31' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/konkurs/vivado_projekty/klt_pyramid/klt_pyramid.srcs/sources_1/ip/prev_context_roi31/prev_context_roi31_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'prev_context_roi31'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
