# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/konkurs/vivado_projekty/klt_pyramid/klt_pyramid.srcs/sources_1/ip/stream_halter_fifo/stream_halter_fifo.xci
# IP: The module: 'stream_halter_fifo' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/konkurs/vivado_projekty/klt_pyramid/klt_pyramid.srcs/sources_1/ip/stream_halter_fifo/stream_halter_fifo.xdc
# XDC: The top module name and the constraint reference have the same name: 'stream_halter_fifo'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/konkurs/vivado_projekty/klt_pyramid/klt_pyramid.srcs/sources_1/ip/stream_halter_fifo/stream_halter_fifo_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'stream_halter_fifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: C:/konkurs/vivado_projekty/klt_pyramid/klt_pyramid.srcs/sources_1/ip/stream_halter_fifo/stream_halter_fifo.xci
# IP: The module: 'stream_halter_fifo' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/konkurs/vivado_projekty/klt_pyramid/klt_pyramid.srcs/sources_1/ip/stream_halter_fifo/stream_halter_fifo.xdc
# XDC: The top module name and the constraint reference have the same name: 'stream_halter_fifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/konkurs/vivado_projekty/klt_pyramid/klt_pyramid.srcs/sources_1/ip/stream_halter_fifo/stream_halter_fifo_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'stream_halter_fifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
