# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/inne/Zybo-Z7-Master.xdc

# Block Designs: bd/tor_wizyjny/tor_wizyjny.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==tor_wizyjny || ORIG_REF_NAME==tor_wizyjny} -quiet] -quiet

# IP: bd/tor_wizyjny/ip/tor_wizyjny_rgb2dvi_0_0/tor_wizyjny_rgb2dvi_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==tor_wizyjny_rgb2dvi_0_0 || ORIG_REF_NAME==tor_wizyjny_rgb2dvi_0_0} -quiet] -quiet

# IP: bd/tor_wizyjny/ip/tor_wizyjny_clk_wiz_0_0/tor_wizyjny_clk_wiz_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==tor_wizyjny_clk_wiz_0_0 || ORIG_REF_NAME==tor_wizyjny_clk_wiz_0_0} -quiet] -quiet

# IP: bd/tor_wizyjny/ip/tor_wizyjny_xlconstant_0_0/tor_wizyjny_xlconstant_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==tor_wizyjny_xlconstant_0_0 || ORIG_REF_NAME==tor_wizyjny_xlconstant_0_0} -quiet] -quiet

# IP: bd/tor_wizyjny/ip/tor_wizyjny_xlconstant_0_1/tor_wizyjny_xlconstant_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==tor_wizyjny_xlconstant_0_1 || ORIG_REF_NAME==tor_wizyjny_xlconstant_0_1} -quiet] -quiet

# IP: bd/tor_wizyjny/ip/tor_wizyjny_dvi2rgb_0_1/tor_wizyjny_dvi2rgb_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==tor_wizyjny_dvi2rgb_0_1 || ORIG_REF_NAME==tor_wizyjny_dvi2rgb_0_1} -quiet] -quiet

# XDC: bd/tor_wizyjny/tor_wizyjny_ooc.xdc
