# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/vivado_projects/Zybo-Z7-Master.xdc

# Block Designs: bd/main_design/main_design.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==main_design || ORIG_REF_NAME==main_design} -quiet] -quiet

# IP: bd/main_design/ip/main_design_dvi2rgb_0_0/main_design_dvi2rgb_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==main_design_dvi2rgb_0_0 || ORIG_REF_NAME==main_design_dvi2rgb_0_0} -quiet] -quiet

# IP: bd/main_design/ip/main_design_rgb2dvi_0_0/main_design_rgb2dvi_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==main_design_rgb2dvi_0_0 || ORIG_REF_NAME==main_design_rgb2dvi_0_0} -quiet] -quiet

# IP: bd/main_design/ip/main_design_clk_wiz_0_0/main_design_clk_wiz_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==main_design_clk_wiz_0_0 || ORIG_REF_NAME==main_design_clk_wiz_0_0} -quiet] -quiet

# IP: bd/main_design/ip/main_design_xlconstant_0_0/main_design_xlconstant_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==main_design_xlconstant_0_0 || ORIG_REF_NAME==main_design_xlconstant_0_0} -quiet] -quiet

# IP: bd/main_design/ip/main_design_xlconstant_1_0/main_design_xlconstant_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==main_design_xlconstant_1_0 || ORIG_REF_NAME==main_design_xlconstant_1_0} -quiet] -quiet

# IP: bd/main_design/ip/main_design_xlconstant_2_0/main_design_xlconstant_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==main_design_xlconstant_2_0 || ORIG_REF_NAME==main_design_xlconstant_2_0} -quiet] -quiet

# IP: bd/main_design/ip/main_design_klt_tracker_w10b2_mu_0_0/main_design_klt_tracker_w10b2_mu_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==main_design_klt_tracker_w10b2_mu_0_0 || ORIG_REF_NAME==main_design_klt_tracker_w10b2_mu_0_0} -quiet] -quiet

# IP: bd/main_design/ip/main_design_rgb2ycbcr_0_0/main_design_rgb2ycbcr_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==main_design_rgb2ycbcr_0_0 || ORIG_REF_NAME==main_design_rgb2ycbcr_0_0} -quiet] -quiet

# IP: bd/main_design/ip/main_design_xlconstant_1_1/main_design_xlconstant_1_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==main_design_xlconstant_1_1 || ORIG_REF_NAME==main_design_xlconstant_1_1} -quiet] -quiet

# IP: bd/main_design/ip/main_design_xlconstant_3_0/main_design_xlconstant_3_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==main_design_xlconstant_3_0 || ORIG_REF_NAME==main_design_xlconstant_3_0} -quiet] -quiet

# XDC: bd/main_design/main_design_ooc.xdc
