# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/konkurs/vivado_projekty/klt_pyramid/klt_pyramid.srcs/sources_1/ip/klt_tracker_w10b2_mult_0/klt_tracker_w10b2_mult_0.xci
# IP: The module: 'klt_tracker_w10b2_mult_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/konkurs/vivado_projekty/klt_pyramid/klt_pyramid.srcs/sources_1/ip/klt_tracker_w10b2_mult_0/src/div_gen_0/div_gen_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==div_gen_0 || ORIG_REF_NAME==div_gen_0} -quiet] -quiet

# IP: c:/konkurs/vivado_projekty/klt_pyramid/klt_pyramid.srcs/sources_1/ip/klt_tracker_w10b2_mult_0/src/sub_52m52/sub_52m52.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==sub_52m52 || ORIG_REF_NAME==sub_52m52} -quiet] -quiet

# IP: c:/konkurs/vivado_projekty/klt_pyramid/klt_pyramid.srcs/sources_1/ip/klt_tracker_w10b2_mult_0/src/mult_26t26/mult_26t26.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mult_26t26 || ORIG_REF_NAME==mult_26t26} -quiet] -quiet

# IP: c:/konkurs/vivado_projekty/klt_pyramid/klt_pyramid.srcs/sources_1/ip/klt_tracker_w10b2_mult_0/src/add_26p18/add_26p18.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==add_26p18 || ORIG_REF_NAME==add_26p18} -quiet] -quiet

# IP: c:/konkurs/vivado_projekty/klt_pyramid/klt_pyramid.srcs/sources_1/ip/klt_tracker_w10b2_mult_0/src/mult_9t9/mult_9t9.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mult_9t9 || ORIG_REF_NAME==mult_9t9} -quiet] -quiet

# IP: c:/konkurs/vivado_projekty/klt_pyramid/klt_pyramid.srcs/sources_1/ip/klt_tracker_w10b2_mult_0/src/sub_8m8/sub_8m8.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==sub_8m8 || ORIG_REF_NAME==sub_8m8} -quiet] -quiet

# IP: c:/konkurs/vivado_projekty/klt_pyramid/klt_pyramid.srcs/sources_1/ip/klt_tracker_w10b2_mult_0/src/frame_delay_sim/frame_delay_sim.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==frame_delay_sim || ORIG_REF_NAME==frame_delay_sim} -quiet] -quiet

# IP: c:/konkurs/vivado_projekty/klt_pyramid/klt_pyramid.srcs/sources_1/ip/klt_tracker_w10b2_mult_0/src/accumulator_adder/accumulator_adder.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==accumulator_adder || ORIG_REF_NAME==accumulator_adder} -quiet] -quiet

# IP: c:/konkurs/vivado_projekty/klt_pyramid/klt_pyramid.srcs/sources_1/ip/klt_tracker_w10b2_mult_0/src/delayLineBRAM/delayLineBRAM.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==delayLineBRAM || ORIG_REF_NAME==delayLineBRAM} -quiet] -quiet

# IP: c:/konkurs/vivado_projekty/klt_pyramid/klt_pyramid.srcs/sources_1/ip/klt_tracker_w10b2_mult_0/src/mult_dy_times_window/mult_dy_times_window.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mult_dy_times_window || ORIG_REF_NAME==mult_dy_times_window} -quiet] -quiet

# XDC: c:/konkurs/vivado_projekty/klt_pyramid/klt_pyramid.srcs/sources_1/ip/klt_tracker_w10b2_mult_0/src/frame_delay_sim/frame_delay_sim_ooc.xdc

# XDC: c:/konkurs/vivado_projekty/klt_pyramid/klt_pyramid.srcs/sources_1/ip/klt_tracker_w10b2_mult_0/src/delayLineBRAM/delayLineBRAM_ooc.xdc

# IP: c:/konkurs/vivado_projekty/klt_pyramid/klt_pyramid.srcs/sources_1/ip/klt_tracker_w10b2_mult_0/klt_tracker_w10b2_mult_0.xci
# IP: The module: 'klt_tracker_w10b2_mult_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/konkurs/vivado_projekty/klt_pyramid/klt_pyramid.srcs/sources_1/ip/klt_tracker_w10b2_mult_0/src/div_gen_0/div_gen_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==div_gen_0 || ORIG_REF_NAME==div_gen_0} -quiet] -quiet

# IP: c:/konkurs/vivado_projekty/klt_pyramid/klt_pyramid.srcs/sources_1/ip/klt_tracker_w10b2_mult_0/src/sub_52m52/sub_52m52.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==sub_52m52 || ORIG_REF_NAME==sub_52m52} -quiet] -quiet

# IP: c:/konkurs/vivado_projekty/klt_pyramid/klt_pyramid.srcs/sources_1/ip/klt_tracker_w10b2_mult_0/src/mult_26t26/mult_26t26.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mult_26t26 || ORIG_REF_NAME==mult_26t26} -quiet] -quiet

# IP: c:/konkurs/vivado_projekty/klt_pyramid/klt_pyramid.srcs/sources_1/ip/klt_tracker_w10b2_mult_0/src/add_26p18/add_26p18.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==add_26p18 || ORIG_REF_NAME==add_26p18} -quiet] -quiet

# IP: c:/konkurs/vivado_projekty/klt_pyramid/klt_pyramid.srcs/sources_1/ip/klt_tracker_w10b2_mult_0/src/mult_9t9/mult_9t9.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mult_9t9 || ORIG_REF_NAME==mult_9t9} -quiet] -quiet

# IP: c:/konkurs/vivado_projekty/klt_pyramid/klt_pyramid.srcs/sources_1/ip/klt_tracker_w10b2_mult_0/src/sub_8m8/sub_8m8.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==sub_8m8 || ORIG_REF_NAME==sub_8m8} -quiet] -quiet

# IP: c:/konkurs/vivado_projekty/klt_pyramid/klt_pyramid.srcs/sources_1/ip/klt_tracker_w10b2_mult_0/src/frame_delay_sim/frame_delay_sim.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==frame_delay_sim || ORIG_REF_NAME==frame_delay_sim} -quiet] -quiet

# IP: c:/konkurs/vivado_projekty/klt_pyramid/klt_pyramid.srcs/sources_1/ip/klt_tracker_w10b2_mult_0/src/accumulator_adder/accumulator_adder.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==accumulator_adder || ORIG_REF_NAME==accumulator_adder} -quiet] -quiet

# IP: c:/konkurs/vivado_projekty/klt_pyramid/klt_pyramid.srcs/sources_1/ip/klt_tracker_w10b2_mult_0/src/delayLineBRAM/delayLineBRAM.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==delayLineBRAM || ORIG_REF_NAME==delayLineBRAM} -quiet] -quiet

# IP: c:/konkurs/vivado_projekty/klt_pyramid/klt_pyramid.srcs/sources_1/ip/klt_tracker_w10b2_mult_0/src/mult_dy_times_window/mult_dy_times_window.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mult_dy_times_window || ORIG_REF_NAME==mult_dy_times_window} -quiet] -quiet

# XDC: c:/konkurs/vivado_projekty/klt_pyramid/klt_pyramid.srcs/sources_1/ip/klt_tracker_w10b2_mult_0/src/frame_delay_sim/frame_delay_sim_ooc.xdc

# XDC: c:/konkurs/vivado_projekty/klt_pyramid/klt_pyramid.srcs/sources_1/ip/klt_tracker_w10b2_mult_0/src/delayLineBRAM/delayLineBRAM_ooc.xdc
