# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: E:/rzeczy/vivado_projekty/klt_ddc/klt_ddc.srcs/sources_1/ip/rgb2ycbcr_0/rgb2ycbcr_0.xci
# IP: The module: 'rgb2ycbcr_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: e:/rzeczy/vivado_projekty/klt_ddc/klt_ddc.srcs/sources_1/ip/rgb2ycbcr_0/src/mult_gen_0/mult_gen_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mult_gen_0 || ORIG_REF_NAME==mult_gen_0} -quiet] -quiet

# IP: e:/rzeczy/vivado_projekty/klt_ddc/klt_ddc.srcs/sources_1/ip/rgb2ycbcr_0/src/c_addsub_0/c_addsub_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==c_addsub_0 || ORIG_REF_NAME==c_addsub_0} -quiet] -quiet

# IP: E:/rzeczy/vivado_projekty/klt_ddc/klt_ddc.srcs/sources_1/ip/rgb2ycbcr_0/rgb2ycbcr_0.xci
# IP: The module: 'rgb2ycbcr_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: e:/rzeczy/vivado_projekty/klt_ddc/klt_ddc.srcs/sources_1/ip/rgb2ycbcr_0/src/mult_gen_0/mult_gen_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mult_gen_0 || ORIG_REF_NAME==mult_gen_0} -quiet] -quiet

# IP: e:/rzeczy/vivado_projekty/klt_ddc/klt_ddc.srcs/sources_1/ip/rgb2ycbcr_0/src/c_addsub_0/c_addsub_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==c_addsub_0 || ORIG_REF_NAME==c_addsub_0} -quiet] -quiet
