#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2018.3 (64-bit)
#
# Filename    : elaborate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for elaborating the compiled design
#
# Generated by Vivado on Wed Mar 27 16:40:40 CET 2019
# SW Build 2405991 on Thu Dec  6 23:36:41 MST 2018
#
# Copyright 1986-2018 Xilinx, Inc. All Rights Reserved.
#
# usage: elaborate.sh
#
# ****************************************************************************
ExecStep()
{
"$@"
RETVAL=$?
if [ $RETVAL -ne 0 ]
then
exit $RETVAL
fi
}
ExecStep xelab -wto 5485c5837faa4ed59fc9d024dcbc8822 --incr --debug typical --relax --mt 8 --include "../../../../klt_ddc.ip_user_files/bd/tor_wizyjny/ip/tor_wizyjny_xlconstant_0_0/sim" --include "../../../../klt_ddc.ip_user_files/bd/tor_wizyjny/ip/tor_wizyjny_xlconstant_0_1/sim" -L blk_mem_gen_v8_4_2 -L xil_defaultlib -L xbip_utils_v3_0_9 -L c_reg_fd_v12_0_5 -L xbip_dsp48_wrapper_v3_0_4 -L xbip_pipe_v3_0_5 -L xbip_dsp48_addsub_v3_0_5 -L xbip_addsub_v3_0_5 -L c_addsub_v12_0_12 -L unisims_ver -L unimacro_ver -L secureip -L xpm --snapshot tb_pyramid_behav xil_defaultlib.tb_pyramid xil_defaultlib.glbl -log elaborate.log
