# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/konkurs/vivado_projekty/czysty_tor/mainVideoProcessing_Zybo-Z20.srcs/sources_1/bd/mainBlockDesign/ip/mainBlockDesign_rgb2ycbcr_0_0/mainBlockDesign_rgb2ycbcr_0_0.xci
# IP: The module: 'mainBlockDesign_rgb2ycbcr_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/konkurs/vivado_projekty/czysty_tor/mainVideoProcessing_Zybo-Z20.srcs/sources_1/bd/mainBlockDesign/ip/mainBlockDesign_rgb2ycbcr_0_0/src/mult_gen_0/mult_gen_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mult_gen_0 || ORIG_REF_NAME==mult_gen_0} -quiet] -quiet

# IP: c:/konkurs/vivado_projekty/czysty_tor/mainVideoProcessing_Zybo-Z20.srcs/sources_1/bd/mainBlockDesign/ip/mainBlockDesign_rgb2ycbcr_0_0/src/c_addsub_0/c_addsub_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==c_addsub_0 || ORIG_REF_NAME==c_addsub_0} -quiet] -quiet

# IP: c:/konkurs/vivado_projekty/czysty_tor/mainVideoProcessing_Zybo-Z20.srcs/sources_1/bd/mainBlockDesign/ip/mainBlockDesign_rgb2ycbcr_0_0/mainBlockDesign_rgb2ycbcr_0_0.xci
# IP: The module: 'mainBlockDesign_rgb2ycbcr_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/konkurs/vivado_projekty/czysty_tor/mainVideoProcessing_Zybo-Z20.srcs/sources_1/bd/mainBlockDesign/ip/mainBlockDesign_rgb2ycbcr_0_0/src/mult_gen_0/mult_gen_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mult_gen_0 || ORIG_REF_NAME==mult_gen_0} -quiet] -quiet

# IP: c:/konkurs/vivado_projekty/czysty_tor/mainVideoProcessing_Zybo-Z20.srcs/sources_1/bd/mainBlockDesign/ip/mainBlockDesign_rgb2ycbcr_0_0/src/c_addsub_0/c_addsub_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==c_addsub_0 || ORIG_REF_NAME==c_addsub_0} -quiet] -quiet
