# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: E:/rzeczy/vivado_projekty/klt_ddc/klt_ddc.srcs/sources_1/ip/mult_26t26/mult_26t26.xci
# IP: The module: 'mult_26t26' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/rzeczy/vivado_projekty/klt_ddc/klt_ddc.srcs/sources_1/ip/mult_26t26/mult_26t26_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'mult_26t26'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: E:/rzeczy/vivado_projekty/klt_ddc/klt_ddc.srcs/sources_1/ip/mult_26t26/mult_26t26.xci
# IP: The module: 'mult_26t26' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/rzeczy/vivado_projekty/klt_ddc/klt_ddc.srcs/sources_1/ip/mult_26t26/mult_26t26_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'mult_26t26'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
