# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: e:/konkurs/vivado_projekty/klt_ddc/klt_ddc.srcs/sources_1/ip/adder_10p10e10/adder_10p10e10.xci
# IP: The module: 'adder_10p10e10' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/konkurs/vivado_projekty/klt_ddc/klt_ddc.srcs/sources_1/ip/adder_10p10e10/adder_10p10e10_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'adder_10p10e10'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: e:/konkurs/vivado_projekty/klt_ddc/klt_ddc.srcs/sources_1/ip/adder_10p10e10/adder_10p10e10.xci
# IP: The module: 'adder_10p10e10' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/konkurs/vivado_projekty/klt_ddc/klt_ddc.srcs/sources_1/ip/adder_10p10e10/adder_10p10e10_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'adder_10p10e10'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
