# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/konkurs/vivado_projekty/ZyboZ7_vision/ZyboZ7_vision.srcs/sources_1/bd/main_design/ip/main_design_dvi2rgb_0_0/main_design_dvi2rgb_0_0.xci
# IP: The module: 'main_design_dvi2rgb_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/konkurs/vivado_projekty/ZyboZ7_vision/ZyboZ7_vision.srcs/sources_1/bd/main_design/ip/main_design_dvi2rgb_0_0/src/dvi2rgb.xdc
# XDC: The top module name and the constraint reference have the same name: 'main_design_dvi2rgb_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/konkurs/vivado_projekty/ZyboZ7_vision/ZyboZ7_vision.srcs/sources_1/bd/main_design/ip/main_design_dvi2rgb_0_0/src/dvi2rgb_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'main_design_dvi2rgb_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: C:/konkurs/vivado_projekty/ZyboZ7_vision/ZyboZ7_vision.srcs/sources_1/bd/main_design/ip/main_design_dvi2rgb_0_0/main_design_dvi2rgb_0_0.xci
# IP: The module: 'main_design_dvi2rgb_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/konkurs/vivado_projekty/ZyboZ7_vision/ZyboZ7_vision.srcs/sources_1/bd/main_design/ip/main_design_dvi2rgb_0_0/src/dvi2rgb.xdc
# XDC: The top module name and the constraint reference have the same name: 'main_design_dvi2rgb_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/konkurs/vivado_projekty/ZyboZ7_vision/ZyboZ7_vision.srcs/sources_1/bd/main_design/ip/main_design_dvi2rgb_0_0/src/dvi2rgb_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'main_design_dvi2rgb_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
