# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/konkurs/vivado_projekty/klt_pyramid/klt_pyramid.srcs/sources_1/ip/sub_52m52/sub_52m52.xci
# IP: The module: 'sub_52m52' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/konkurs/vivado_projekty/klt_pyramid/klt_pyramid.srcs/sources_1/ip/sub_52m52/sub_52m52_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'sub_52m52'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: C:/konkurs/vivado_projekty/klt_pyramid/klt_pyramid.srcs/sources_1/ip/sub_52m52/sub_52m52.xci
# IP: The module: 'sub_52m52' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/konkurs/vivado_projekty/klt_pyramid/klt_pyramid.srcs/sources_1/ip/sub_52m52/sub_52m52_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'sub_52m52'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
