# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/inne/Zybo_HDMI.xdc

# Block Designs: bd/design_1/design_1.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1 || ORIG_REF_NAME==design_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_rgb2vga_0_0/design_1_rgb2vga_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_rgb2vga_0_0 || ORIG_REF_NAME==design_1_rgb2vga_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_dvi2rgb_0_0/design_1_dvi2rgb_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_dvi2rgb_0_0 || ORIG_REF_NAME==design_1_dvi2rgb_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_clk_wiz_0_0/design_1_clk_wiz_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_clk_wiz_0_0 || ORIG_REF_NAME==design_1_clk_wiz_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xlconstant_0_0/design_1_xlconstant_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xlconstant_0_0 || ORIG_REF_NAME==design_1_xlconstant_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xlconstant_1_0/design_1_xlconstant_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xlconstant_1_0 || ORIG_REF_NAME==design_1_xlconstant_1_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xlconstant_1_2/design_1_xlconstant_1_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xlconstant_1_2 || ORIG_REF_NAME==design_1_xlconstant_1_2} -quiet] -quiet

# IP: bd/design_1/ip/design_1_rgb2ycbcr_0_0/design_1_rgb2ycbcr_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_rgb2ycbcr_0_0 || ORIG_REF_NAME==design_1_rgb2ycbcr_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_rgb2ycbcr_0_0/src/mult_gen_0/mult_gen_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mult_gen_0 || ORIG_REF_NAME==mult_gen_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_rgb2ycbcr_0_0/src/c_addsub_0/c_addsub_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==c_addsub_0 || ORIG_REF_NAME==c_addsub_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_processing_system7_0_0/design_1_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_processing_system7_0_0 || ORIG_REF_NAME==design_1_processing_system7_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_parameter_register_0_0/design_1_parameter_register_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_parameter_register_0_0 || ORIG_REF_NAME==design_1_parameter_register_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_ps7_0_axi_periph_0/design_1_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_ps7_0_axi_periph_0 || ORIG_REF_NAME==design_1_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_rst_ps7_0_100M_0/design_1_rst_ps7_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_rst_ps7_0_100M_0 || ORIG_REF_NAME==design_1_rst_ps7_0_100M_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_bin_mask_0_0/design_1_bin_mask_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_bin_mask_0_0 || ORIG_REF_NAME==design_1_bin_mask_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_centroid_0_0/design_1_centroid_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_centroid_0_0 || ORIG_REF_NAME==design_1_centroid_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_centroid_0_0/src/divider_32_20_0/divider_32_20_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==divider_32_20_0 || ORIG_REF_NAME==divider_32_20_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_centroid_0_0/src/divider_32_20_0/src/mult_32_20_lm/mult_32_20_lm.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mult_32_20_lm || ORIG_REF_NAME==mult_32_20_lm} -quiet] -quiet

# IP: bd/design_1/ip/design_1_wysw_0_0/design_1_wysw_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_wysw_0_0 || ORIG_REF_NAME==design_1_wysw_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xlconcat_0_0/design_1_xlconcat_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xlconcat_0_0 || ORIG_REF_NAME==design_1_xlconcat_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_mux_0_0/design_1_mux_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_mux_0_0 || ORIG_REF_NAME==design_1_mux_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_bbox21_0_0/design_1_bbox21_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_bbox21_0_0 || ORIG_REF_NAME==design_1_bbox21_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_KLT_2200_0_0/design_1_KLT_2200_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_KLT_2200_0_0 || ORIG_REF_NAME==design_1_KLT_2200_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_KLT_2200_0_0/src/delayLineBRAM/delayLineBRAM.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==delayLineBRAM || ORIG_REF_NAME==delayLineBRAM} -quiet] -quiet

# IP: bd/design_1/ip/design_1_KLT_2200_0_0/src/div_gen_0/div_gen_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==div_gen_0 || ORIG_REF_NAME==div_gen_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_KLT_2200_0_0/src/sub_52m52/sub_52m52.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==sub_52m52 || ORIG_REF_NAME==sub_52m52} -quiet] -quiet

# IP: bd/design_1/ip/design_1_KLT_2200_0_0/src/mult_26t26/mult_26t26.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mult_26t26 || ORIG_REF_NAME==mult_26t26} -quiet] -quiet

# IP: bd/design_1/ip/design_1_KLT_2200_0_0/src/add_26p18/add_26p18.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==add_26p18 || ORIG_REF_NAME==add_26p18} -quiet] -quiet

# IP: bd/design_1/ip/design_1_KLT_2200_0_0/src/mult_9t9/mult_9t9.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mult_9t9 || ORIG_REF_NAME==mult_9t9} -quiet] -quiet

# IP: bd/design_1/ip/design_1_KLT_2200_0_0/src/sub_8m8/sub_8m8.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==sub_8m8 || ORIG_REF_NAME==sub_8m8} -quiet] -quiet

# IP: bd/design_1/ip/design_1_KLT_2200_0_0/src/frame_delay_sim/frame_delay_sim.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==frame_delay_sim || ORIG_REF_NAME==frame_delay_sim} -quiet] -quiet

# IP: bd/design_1/ip/design_1_KLT_2200_0_0/src/mult_dy_times_window/mult_dy_times_window.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mult_dy_times_window || ORIG_REF_NAME==mult_dy_times_window} -quiet] -quiet

# IP: bd/design_1/ip/design_1_KLT_2200_0_0/src/accumulator_adder/accumulator_adder.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==accumulator_adder || ORIG_REF_NAME==accumulator_adder} -quiet] -quiet

# IP: bd/design_1/ip/design_1_split_rgb_0_0/design_1_split_rgb_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_split_rgb_0_0 || ORIG_REF_NAME==design_1_split_rgb_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xlconstant_1_1/design_1_xlconstant_1_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xlconstant_1_1 || ORIG_REF_NAME==design_1_xlconstant_1_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xlconstant_1_3/design_1_xlconstant_1_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xlconstant_1_3 || ORIG_REF_NAME==design_1_xlconstant_1_3} -quiet] -quiet

# IP: bd/design_1/ip/design_1_system_ila_0_1/design_1_system_ila_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_system_ila_0_1 || ORIG_REF_NAME==design_1_system_ila_0_1} -quiet] -quiet

# Block Designs: bd/design_1/ip/design_1_system_ila_0_1/bd_0/bd_36cd.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_36cd || ORIG_REF_NAME==bd_36cd} -quiet] -quiet

# IP: bd/design_1/ip/design_1_system_ila_0_1/bd_0/ip/ip_0/bd_36cd_ila_lib_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_36cd_ila_lib_0 || ORIG_REF_NAME==bd_36cd_ila_lib_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_auto_pc_0/design_1_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_auto_pc_0 || ORIG_REF_NAME==design_1_auto_pc_0} -quiet] -quiet

# XDC: bd/design_1/ip/design_1_dvi2rgb_0_0/src/dvi2rgb.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_dvi2rgb_0_0 || ORIG_REF_NAME==design_1_dvi2rgb_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/design_1/ip/design_1_dvi2rgb_0_0/src/dvi2rgb_ooc.xdc

# XDC: bd/design_1/ip/design_1_clk_wiz_0_0/design_1_clk_wiz_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_clk_wiz_0_0 || ORIG_REF_NAME==design_1_clk_wiz_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/design_1/ip/design_1_clk_wiz_0_0/design_1_clk_wiz_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_clk_wiz_0_0 || ORIG_REF_NAME==design_1_clk_wiz_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/design_1/ip/design_1_clk_wiz_0_0/design_1_clk_wiz_0_0_ooc.xdc

# XDC: bd/design_1/ip/design_1_processing_system7_0_0/design_1_processing_system7_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_processing_system7_0_0 || ORIG_REF_NAME==design_1_processing_system7_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/design_1/ip/design_1_rst_ps7_0_100M_0/design_1_rst_ps7_0_100M_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_rst_ps7_0_100M_0 || ORIG_REF_NAME==design_1_rst_ps7_0_100M_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/design_1/ip/design_1_rst_ps7_0_100M_0/design_1_rst_ps7_0_100M_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_rst_ps7_0_100M_0 || ORIG_REF_NAME==design_1_rst_ps7_0_100M_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/design_1/ip/design_1_rst_ps7_0_100M_0/design_1_rst_ps7_0_100M_0_ooc.xdc

# XDC: bd/design_1/ip/design_1_KLT_2200_0_0/src/delayLineBRAM/delayLineBRAM_ooc.xdc

# XDC: bd/design_1/ip/design_1_KLT_2200_0_0/src/frame_delay_sim/frame_delay_sim_ooc.xdc

# XDC: bd/design_1/ip/design_1_system_ila_0_1/bd_0/ip/ip_0/ila_v6_2/constraints/ila_impl.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_36cd_ila_lib_0 || ORIG_REF_NAME==bd_36cd_ila_lib_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/design_1/ip/design_1_system_ila_0_1/bd_0/ip/ip_0/ila_v6_2/constraints/ila.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_36cd_ila_lib_0 || ORIG_REF_NAME==bd_36cd_ila_lib_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/design_1/ip/design_1_system_ila_0_1/bd_0/ip/ip_0/bd_36cd_ila_lib_0_ooc.xdc

# XDC: bd/design_1/ip/design_1_system_ila_0_1/bd_0/bd_36cd_ooc.xdc

# XDC: bd/design_1/ip/design_1_system_ila_0_1/design_1_system_ila_0_1_ooc.xdc

# XDC: bd/design_1/ip/design_1_auto_pc_0/design_1_auto_pc_0_ooc.xdc

# XDC: bd/design_1/design_1_ooc.xdc
