webtalk_init -webtalk_dir E:/rzeczy/vivado_projekty/tor_wizyjny/tor_wizyjny.sim/sim_1/behav/xsim/xsim.dir/tb_hdmi_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Thu Dec  6 22:32:37 2018" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2018.2 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2258646" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "82e14c6f-ecda-43a4-9f69-b974bb3c9b9b" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "792f08ed8ecf47e2834e87a18db87ad9" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "40" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 7 , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "Service Pack 1  (build 7601)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i5-2500K CPU @ 3.30GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "3292 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "4.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "100 us" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "2" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "3.15_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "16024_KB" -context "xsim\\usage"
webtalk_transmit -clientid 3230863264 -regid "" -xml E:/rzeczy/vivado_projekty/tor_wizyjny/tor_wizyjny.sim/sim_1/behav/xsim/xsim.dir/tb_hdmi_behav/webtalk/usage_statistics_ext_xsim.xml -html E:/rzeczy/vivado_projekty/tor_wizyjny/tor_wizyjny.sim/sim_1/behav/xsim/xsim.dir/tb_hdmi_behav/webtalk/usage_statistics_ext_xsim.html -wdm E:/rzeczy/vivado_projekty/tor_wizyjny/tor_wizyjny.sim/sim_1/behav/xsim/xsim.dir/tb_hdmi_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
